server:
    port: 8080
spring:
    jpa:
        database: mysql
    datasource:
        url: jdbc:mysql://localhost:3306/auto_sales?useUnicode=true&characterEncoding=UTF-8&useSSL=true
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        tomcat:
            min-idle: 1
            max-active: 20
            initial-size: 1
            time-between-eviction-runs-millis: 3000
            min-evictable-idle-time-millis: 300000
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
mybatis:
    # mybatis扫描
    mapper-locations: classpath*:mapper/*.xml
    # 起别名.可省略mybatis的xml中的resultType的全路径
    type-aliases-package: com.cnty.auto.pojo
    configuration:
        map-underscore-to-camel-case: true